import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google"; //Получаем шрифты из google fonts
import "./globals.css";

const notoSans = Noto_Sans({
  // Настроеваем шрифты
  subsets: ["latin", "cyrillic"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-family",
  display: "swap",
});

export const metadata: Metadata = {
  title: "My project ",
  description: "Generated by create next app",
  openGraph: {},
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //Подключаем шрифты через перемменые
  return (
    <html lang="ru">
      <body className={`${notoSans.variable}`}>{children}</body>
    </html>
  );
}

//title: 'Наш проект'
//title: 'Исправльенный'
